version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Map the React app to local port 3000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "mysql://root:root@db/wikigrapher"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wikigrapher
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
